2023-04-20 00:23:08.174 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-20 00:23:08.187 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-20 00:24:36.503 WARNING (MainThread) [homeassistant.setup] Setup of image_upload is taking over 10 seconds.
2023-04-20 00:24:37.951 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-04-20 00:24:38.728 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=54 from 2023-04-14 19:53:34.916907)
2023-04-20 00:24:54.197 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2023-04-20 00:25:00.908 WARNING (MainThread) [homeassistant.setup] Setup of bluetooth is taking over 10 seconds.
2023-04-20 00:25:11.878 WARNING (MainThread) [homeassistant.components.systemmonitor.sensor] Cannot read CPU / processor temperature information
2023-04-20 00:25:22.000 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for hacs using this method at custom_components/hacs/__init__.py, line 171: hass.config_entries.async_setup_platforms(
2023-04-20 00:25:22.423 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Samsung C48x Series (SEC30CDA7AC8DD0)' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2023-04-20 06:44:35.029 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.100168336c_1 or it is/they are currently not available
2023-04-20 20:45:31.466 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.100168336c_1 or it is/they are currently not available
2023-04-20 20:46:00.208 ERROR (MainThread) [frontend.js.latest.202304111] https://ha.sebright.synology.me/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:57:95 TypeError: null is not an object (evaluating 'e.querySelector')
2023-04-20 23:19:53.262 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.100168336c_1 or it is/they are currently not available
2023-04-21 20:47:09.741 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.100168336c_1 or it is/they are currently not available
2023-04-21 20:47:43.782 ERROR (MainThread) [frontend.js.latest.202304111] https://ha.sebright.synology.me/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:57:95 TypeError: null is not an object (evaluating 'e.querySelector')
2023-04-21 20:48:15.304 ERROR (MainThread) [frontend.js.latest.202304111] https://ha.sebright.synology.me/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:13:51 TypeError: null is not an object (evaluating 'e.shadowRoot.querySelector("hui-root").shadowRoot')
2023-04-21 20:48:30.523 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.100168336c_1 or it is/they are currently not available
2023-04-21 20:48:31.484 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.100168336c_1 or it is/they are currently not available
2023-04-21 20:50:08.302 ERROR (MainThread) [frontend.js.latest.202304111] https://ha.sebright.synology.me/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:57:95 TypeError: null is not an object (evaluating 'e.querySelector')
2023-04-21 20:50:41.629 ERROR (MainThread) [frontend.js.latest.202304111] https://ha.sebright.synology.me/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:13:51 TypeError: null is not an object (evaluating 'e.shadowRoot.querySelector("hui-root").shadowRoot')
2023-04-21 20:55:54.170 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2023-04-21 20:55:54.646 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2023-04-21 20:57:17.603 WARNING (MainThread) [homeassistant.core] Task <Task pending name='Task-406979' coro=<ServiceRegistry._run_service_in_background.<locals>.catch_exceptions() running at /usr/src/homeassistant/homeassistant/core.py:1838> wait_for=<Task pending name='Task-406949' coro=<ServiceRegistry._execute_service() running at /usr/src/homeassistant/homeassistant/core.py:1857> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove(), Task.task_wakeup()]> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
2023-04-21 20:57:17.627 WARNING (MainThread) [homeassistant.core] Task <Task pending name='Task-406951' coro=<async_install() running at /usr/src/homeassistant/homeassistant/components/update/__init__.py:156> wait_for=<Future finished exception=ServerDisconnectedError('Server disconnected')> cb=[set.remove(), Task.task_wakeup()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
2023-04-21 20:57:18.934 WARNING (Thread-5 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_17] is still running at shutdown: File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81, in _worker
    work_item = work_queue.get(block=True)
